# Generated by Django 4.2.5 on 2023-09-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(max_length=20, verbose_name="Категория рецепта"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipe.categories",
            ),
        ),
    ]
