# Generated by Django 4.2.5 on 2023-09-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_alter_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.CharField(null=True, verbose_name="Время приготовления"),
        ),
    ]
