# Generated by Django 4.2.5 on 2023-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                max_length=500, verbose_name="Описание приготовления"
            ),
        ),
    ]
