# Generated by Django 4.2.5 on 2023-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_alter_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(max_length=500, verbose_name="Ингридиенты"),
        ),
    ]
