# Generated by Django 4.2.5 on 2023-09-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0010_alter_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(
                null=True, verbose_name="Время приготовления в минутах"
            ),
        ),
    ]
