# Generated by Django 4.2.5 on 2023-09-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0012_alter_recipe_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.RemoveField(model_name="subscription", name="user",),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                max_length=3000, verbose_name="Способ приготовления"
            ),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_id", models.IntegerField(verbose_name="ID пользователя")),
                (
                    "username",
                    models.CharField(max_length=200, verbose_name="Имя пользователя"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_subscriptions",
                        to="recipe.subscription",
                    ),
                ),
            ],
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты",},
        ),
        migrations.AlterUniqueTogether(name="likedislike", unique_together=set(),),
        migrations.AddField(
            model_name="likedislike",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipe.client",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="recipe.client",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="likedislike", unique_together={("client", "recipe", "action")},
        ),
        migrations.RemoveField(model_name="likedislike", name="user",),
        migrations.DeleteModel(name="User",),
    ]
