# Generated by Django 4.2.5 on 2023-09-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0013_alter_categories_options_remove_subscription_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name": "Рецепт", "verbose_name_plural": "Рецепты"},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(
                default="Клиент", max_length=20, verbose_name="Имя в тг"
            ),
        ),
    ]
