# Generated by Django 4.2.5 on 2023-09-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0015_subscription_subscription_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="subscription",),
    ]
