# Generated by Django 4.2.5 on 2023-09-20 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0016_remove_client_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCategoryView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views_left", models.IntegerField(default=3)),
                ("date", models.DateField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipe.categories",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_views",
                        to="recipe.client",
                    ),
                ),
            ],
            options={"unique_together": {("user", "category", "date")},},
        ),
    ]
