# Generated by Django 4.2.5 on 2023-09-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0017_usercategoryview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="tg_id",
            field=models.BigIntegerField(verbose_name="ID пользователя"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата подписки"),
        ),
    ]
