# Generated by Django 4.2.5 on 2023-09-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0018_alter_client_tg_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="username",
            field=models.CharField(
                max_length=200, verbose_name="Username пользователя"
            ),
        ),
    ]
