# Generated by Django 4.2.5 on 2023-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0020_userlimitview_delete_usercategoryview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_duration",
            field=models.DateTimeField(
                default=None, verbose_name="Длительность подписки"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_is_active",
            field=models.BooleanField(default=False, verbose_name="Подписка"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
