# Generated by Django 4.2.5 on 2023-09-22 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0022_remove_subscription_subscription_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscription_duration",
            field=models.DurationField(
                default=datetime.timedelta(0), verbose_name="Длительность подписки"
            ),
        ),
    ]
