# Generated by Django 4.2.5 on 2023-09-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0023_subscription_subscription_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата подписки"),
        ),
    ]
